### ISSUE TITLE
style bug: Background is translucent when generating text

### ISSUE THREAD

**Issue by zcf0508** [onepointAI/onepoint#10]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/21942252/233054945-51c29cd4-47a6-432b-9bdc-d799f2812621.png">

**Comment by boxizen** [comment]
Could you describe how to reproduce this issue, please?

**Comment by zcf0508** [comment]
I just select some text in chrome, and use `cmd+k` open the windows. Then I click `Yes` in the toast.

![image](https://user-images.githubusercontent.com/21942252/233142771-36b77ca3-d348-4a6a-8f31-fdb49a1f086a.png)

**Comment by boxizen** [comment]
> I just select some text in chrome, and use `cmd+k` open the window. Then I click `Yes` in the toast.
> 
> ![image](https://user-images.githubusercontent.com/21942252/233142771-36b77ca3-d348-4a6a-8f31-fdb49a1f086a.png)

Sorry, I still can't reproduce this issue. If possible, would you mind to make a short video to demonstrate it or submit a PR to fix it?

**Comment by boxizen** [comment]
> > I just select some text in chrome, and use `cmd+k` open the window. Then I click `Yes` in the toast.
> > ![image](https://user-images.githubusercontent.com/21942252/233142771-36b77ca3-d348-4a6a-8f31-fdb49a1f086a.png)
> 
> Sorry, I still can't reproduce this issue. If possible, would you mind to make a short video to demonstrate it or submit a PR to fix it?

I have also encountered this issue in production mode, I will fix it today.
