### ISSUE TITLE
大佬，我这边windows电脑提示安装失败，以下是日志，麻烦您看下

### ISSUE THREAD

**Issue by aymanajal** [onepointAI/onepoint#16]
`2312> 2023-03-16 01:35:47> Program: Starting Squirrel Updater: --install .
2312> 2023-03-16 01:35:47> Program: Starting install, writing to C:\Users\eva\AppData\Local\SquirrelTemp
2312> 2023-03-16 01:35:47> Program: About to install to: C:\Users\eva\AppData\Local\Discord
2312> 2023-03-16 01:35:47> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
2312> 2023-03-16 01:35:47> CheckForUpdateImpl: Reading RELEASES file from C:\Users\eva\AppData\Local\SquirrelTemp
2312> 2023-03-16 01:35:47> CheckForUpdateImpl: Remote version 1.0.9011 differs from local 
2312> 2023-03-16 01:35:47> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2312> 2023-03-16 01:35:47> ApplyReleasesImpl: Writing files to app directory: C:\Users\eva\AppData\Local\Discord\app-1.0.9011
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\d3dcompiler_47.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\d3dcompiler_47.dll
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\chrome_100_percent.pak to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\chrome_100_percent.pak
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\chrome_200_percent.pak to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\chrome_200_percent.pak
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\app.ico to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\app.ico
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\Discord.exe to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\ffmpeg.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\ffmpeg.dll
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\icudtl.dat to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\icudtl.dat
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\installer.db to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\installer.db
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\libEGL.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\libEGL.dll
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\libGLESv2.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\libGLESv2.dll
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\resources.pak to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\resources.pak
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\snapshot_blob.bin to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\snapshot_blob.bin
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\updater.node to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\updater.node
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\vk_swiftshader.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\vk_swiftshader.dll
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\vulkan-1.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\vulkan-1.dll
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\vk_swiftshader_icd.json to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\vk_swiftshader_icd.json
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\v8_context_snapshot.bin to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\v8_context_snapshot.bin
2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe]
2312> 2023-03-16 01:35:52> Utility: Process Started: C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe --squirrel-install 1.0.9011, pid 24604
2312> 2023-03-16 01:35:53> Utility: Received exitcode 0 from process C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe
2312> 2023-03-16 01:35:53> ApplyReleasesImpl: ran C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe, pid 12808
2312> 2023-03-16 01:35:53> ApplyReleasesImpl: Starting fixPinnedExecutables
2312> 2023-03-16 01:35:53> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9011
2312> 2023-03-16 01:35:53> ApplyReleasesImpl: fixPinnedExecutables: enumerating path C:\Users\eva\AppData\Roaming\Microsoft\Windows\Start Menu failed: System.UnauthorizedAccessException: 对路径“C:\Users\eva\AppData\Roaming\Microsoft\Windows\Start Menu\程序”的访问被拒绝。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   在 System.IO.FileSystemEnumerableIterator`1.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   在 System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   在 Squirrel.UpdateManager.ApplyReleasesImpl.fixPinnedExecutables(SemanticVersion newCurrentVersion)
2312> 2023-03-16 01:35:53> ApplyReleasesImpl: Updating shortcut C:\Users\eva\Desktop\Discord.lnk
2312> 2023-03-16 01:35:53> ApplyReleasesImpl: Fixing up tray icons
2312> 2023-03-16 01:35:53> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9011
2312> 2023-03-16 01:35:53> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-1.0.9011
2023-04-18 09:34:46> Program: Starting Squirrel Updater: --install .
2023-04-18 09:34:46> Program: Starting install, writing to C:\Users\eva\AppData\Local\SquirrelTemp
2023-04-18 09:34:46> Program: About to install to: C:\Users\eva\AppData\Local\slack
2023-04-18 09:34:46> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\eva\AppData\Local\slack\packages\.betaId”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   在 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   在 System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   在 Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2023-04-18 09:34:46> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\eva\AppData\Local\slack\packages\RELEASES”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   在 Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2023-04-18 09:34:46> CheckForUpdateImpl: Reading RELEASES file from C:\Users\eva\AppData\Local\SquirrelTemp
2023-04-18 09:34:46> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2023-04-18 09:34:46> ApplyReleasesImpl: Writing files to app directory: C:\Users\eva\AppData\Local\slack\app-4.31.155
2023-04-18 09:34:48> LogHost: Rigging execution stub for lib/net45/slack_ExecutionStub.exe to C:\Users\eva\AppData\Local\slack\slack.exe
2023-04-18 09:34:49> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\eva\AppData\Local\slack\app-4.31.155\slack.exe]
2023-04-18 09:34:49> ApplyReleasesImpl: Starting fixPinnedExecutables
2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: ChatGPT Next Web.lnk
2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: Chat酱.lnk
2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: Microsoft Edge.lnk
2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: OneNote.lnk
2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: Outlook.lnk
2023-04-18 09:34:49> ApplyReleasesImpl: Fixing up tray icons
2023-04-18 09:34:49> ApplyReleasesImpl: cleanDeadVersions: for version 4.31.155
2023-04-18 09:34:49> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-4.31.155
`

**Comment by boxizen** [comment]
> `2312> 2023-03-16 01:35:47> Program: Starting Squirrel Updater: --install . 2312> 2023-03-16 01:35:47> Program: Starting install, writing to C:\Users\eva\AppData\Local\SquirrelTemp 2312> 2023-03-16 01:35:47> Program: About to install to: C:\Users\eva\AppData\Local\Discord 2312> 2023-03-16 01:35:47> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10 2312> 2023-03-16 01:35:47> CheckForUpdateImpl: Reading RELEASES file from C:\Users\eva\AppData\Local\SquirrelTemp 2312> 2023-03-16 01:35:47> CheckForUpdateImpl: Remote version 1.0.9011 differs from local 2312> 2023-03-16 01:35:47> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch 2312> 2023-03-16 01:35:47> ApplyReleasesImpl: Writing files to app directory: C:\Users\eva\AppData\Local\Discord\app-1.0.9011 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\d3dcompiler_47.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\d3dcompiler_47.dll 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\chrome_100_percent.pak to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\chrome_100_percent.pak 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\chrome_200_percent.pak to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\chrome_200_percent.pak 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\app.ico to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\app.ico 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\Discord.exe to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\ffmpeg.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\ffmpeg.dll 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\icudtl.dat to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\icudtl.dat 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\installer.db to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\installer.db 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\libEGL.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\libEGL.dll 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\libGLESv2.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\libGLESv2.dll 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\resources.pak to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\resources.pak 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\snapshot_blob.bin to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\snapshot_blob.bin 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\updater.node to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\updater.node 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\vk_swiftshader.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\vk_swiftshader.dll 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\vulkan-1.dll to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\vulkan-1.dll 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\vk_swiftshader_icd.json to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\vk_swiftshader_icd.json 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Moving file C:\Users\eva\AppData\Local\Discord\app-1.0.9011\lib\net45\v8_context_snapshot.bin to C:\Users\eva\AppData\Local\Discord\app-1.0.9011\v8_context_snapshot.bin 2312> 2023-03-16 01:35:51> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe] 2312> 2023-03-16 01:35:52> Utility: Process Started: C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe --squirrel-install 1.0.9011, pid 24604 2312> 2023-03-16 01:35:53> Utility: Received exitcode 0 from process C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe 2312> 2023-03-16 01:35:53> ApplyReleasesImpl: ran C:\Users\eva\AppData\Local\Discord\app-1.0.9011\Discord.exe, pid 12808 2312> 2023-03-16 01:35:53> ApplyReleasesImpl: Starting fixPinnedExecutables 2312> 2023-03-16 01:35:53> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9011 2312> 2023-03-16 01:35:53> ApplyReleasesImpl: fixPinnedExecutables: enumerating path C:\Users\eva\AppData\Roaming\Microsoft\Windows\Start Menu failed: System.UnauthorizedAccessException: 对路径“C:\Users\eva\AppData\Roaming\Microsoft\Windows\Start Menu\程序”的访问被拒绝。 在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 在 System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData) 在 System.IO.FileSystemEnumerableIterator`1.MoveNext() 在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) 在 System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption) 在 System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption) 在 Squirrel.UpdateManager.ApplyReleasesImpl.fixPinnedExecutables(SemanticVersion newCurrentVersion) 2312> 2023-03-16 01:35:53> ApplyReleasesImpl: Updating shortcut C:\Users\eva\Desktop\Discord.lnk 2312> 2023-03-16 01:35:53> ApplyReleasesImpl: Fixing up tray icons 2312> 2023-03-16 01:35:53> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9011 2312> 2023-03-16 01:35:53> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-1.0.9011 2023-04-18 09:34:46> Program: Starting Squirrel Updater: --install . 2023-04-18 09:34:46> Program: Starting install, writing to C:\Users\eva\AppData\Local\SquirrelTemp 2023-04-18 09:34:46> Program: About to install to: C:\Users\eva\AppData\Local\slack 2023-04-18 09:34:46> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\eva\AppData\Local\slack\packages\.betaId”的一部分。 在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) 在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) 在 System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost) 在 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost) 在 System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost) 在 System.IO.File.WriteAllText(String path, String contents, Encoding encoding) 在 Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId() 2023-04-18 09:34:46> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\eva\AppData\Local\slack\packages\RELEASES”的一部分。 在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) 在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) 在 Squirrel.Utility.LoadLocalReleases(String localReleaseFile) 在 Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext() 2023-04-18 09:34:46> CheckForUpdateImpl: Reading RELEASES file from C:\Users\eva\AppData\Local\SquirrelTemp 2023-04-18 09:34:46> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch 2023-04-18 09:34:46> ApplyReleasesImpl: Writing files to app directory: C:\Users\eva\AppData\Local\slack\app-4.31.155 2023-04-18 09:34:48> LogHost: Rigging execution stub for lib/net45/slack_ExecutionStub.exe to C:\Users\eva\AppData\Local\slack\slack.exe 2023-04-18 09:34:49> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\eva\AppData\Local\slack\app-4.31.155\slack.exe] 2023-04-18 09:34:49> ApplyReleasesImpl: Starting fixPinnedExecutables 2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: ChatGPT Next Web.lnk 2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: Chat酱.lnk 2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: File Explorer.lnk 2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: Microsoft Edge.lnk 2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: OneNote.lnk 2023-04-18 09:34:49> ApplyReleasesImpl: Examining Pin: Outlook.lnk 2023-04-18 09:34:49> ApplyReleasesImpl: Fixing up tray icons 2023-04-18 09:34:49> ApplyReleasesImpl: cleanDeadVersions: for version 4.31.155 2023-04-18 09:34:49> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-4.31.155 `

你好，这个问题看起来是 Windows 系统的权限问题，麻烦参考下这篇指引看看是否能解决哈
