### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by yann-lu** [onepointAI/onepoint#17]
<img width="800" alt="image" src="https://github.com/onepointAI/onepoint/assets/56394479/e2e3c705-5931-4d6d-a073-4a26e697373e">

我下载后，只配置了key。其他还需要设置什么，使用一直提示 read ECONNRESET

**Comment by boxizen** [comment]
不需要额外设置了，麻烦看下closeapi.deno.dev是否可以ping通哈
