### ISSUE TITLE
能否搞一个微信讨论群哇？沟通更加直接一点？

### ISSUE THREAD

**Issue by idwalker** [onepointAI/onepoint#18]
国内更流行放一个交流群，这样大家互动方便一点

**Comment by boxizen** [comment]
你好，可以移步到 https://github.com/onepointAI/onepoint/discussions 讨论问题哈，目前用户量不是很多，感觉没有太必要开群，另外直接在 discussions 上讨论也可以方便其他用户浏览历史信息哈
